import LandingRoot from "@/components/home";
import AppWrapper from "@/components/layouts/AppWrapper";
import StepperProvider from "@/context/StepperContext";
import { NextPageWithLayout } from "@/types";
import Head from "next/head";
import React from "react";

const Landing: NextPageWithLayout = () => (
    <>
        <Head>
            <title>Iconify</title>
            <meta name="description" content="Generated by Sayanta" />
        </Head>
        <StepperProvider>
            <LandingRoot />
        </StepperProvider>
    </>
);

Landing.getLayout = (page) => <AppWrapper>{page}</AppWrapper>;

export default Landing;
